jenkins:
  systemMessage: "Welcome to the Whanos Jenkin Platform."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Admin"
          password: "${USER_ADMIN_PASSWORD}"

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "admin"

jobs:
  - file: /var/jenkins_home/job_dsl.groovy
